project:
  type: website
  output-dir: docs

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: visualization.qmd
        text: Visualization

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



