<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Website - FLAT RATE PRICING</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../visualization.html"> 
<span class="menu-text">Visualization</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#nyop-pricing" id="toc-nyop-pricing" class="nav-link active" data-scroll-target="#nyop-pricing">NYOP PRICING</a>
  <ul class="collapse">
  <li><a href="#the-difference-between-nyop-and-nyop-charity-for-those-who-purchase-1-picture" id="toc-the-difference-between-nyop-and-nyop-charity-for-those-who-purchase-1-picture" class="nav-link" data-scroll-target="#the-difference-between-nyop-and-nyop-charity-for-those-who-purchase-1-picture">The difference between NYOP and NYOP Charity for those who purchase 1 picture</a></li>
  <li><a href="#the-difference-between-nyop-and-nyop-charity-for-those-who-purchase-6-pictures" id="toc-the-difference-between-nyop-and-nyop-charity-for-those-who-purchase-6-pictures" class="nav-link" data-scroll-target="#the-difference-between-nyop-and-nyop-charity-for-those-who-purchase-6-pictures">The difference between NYOP and NYOP Charity for those who purchase 6 pictures</a></li>
  </ul></li>
  <li><a href="#economics" id="toc-economics" class="nav-link" data-scroll-target="#economics">Economics</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">FLAT RATE PRICING</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This project using hypothesis to run A/B testing.</p>
<div id="79e6cc5e" class="cell" data-results="hide" data-execution_count="1">
<div class="cell-output cell-output-display" data-execution_count="1">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">NumberSold</th>
<th data-quarto-table-cell-role="th">Riders</th>
<th data-quarto-table-cell-role="th">MerchandiseRevenues</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>FR</td>
<td>77</td>
<td>12663</td>
<td>4592.41</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>FR</td>
<td>63</td>
<td>15561</td>
<td>6688.57</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>FR Charity</td>
<td>79</td>
<td>14796</td>
<td>6476.78</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>FR Charity</td>
<td>101</td>
<td>15796</td>
<td>5845.94</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>NYOP</td>
<td>1137</td>
<td>14077</td>
<td>4845.27</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>NYOP</td>
<td>1233</td>
<td>14186</td>
<td>7038.63</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>NYOP Charity</td>
<td>539</td>
<td>12227</td>
<td>5690.59</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>NYOP Charity</td>
<td>628</td>
<td>13741</td>
<td>6003.44</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>NYOP Charity</td>
<td>626</td>
<td>18117</td>
<td>8557.47</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div id="6e1cd139" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the total sales of each condition</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sales_count <span class="op">=</span> sales.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'NumberSold'</span>].<span class="bu">sum</span>()</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sales_count)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Total sales of all conditions</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>total_sales <span class="op">=</span> sales_count.<span class="bu">sum</span>()</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total_sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Condition
FR               140
FR Charity       180
NYOP            2370
NYOP Charity    1793
Name: NumberSold, dtype: int64
4483</code></pre>
</div>
</div>
<div id="61939887" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#number of sales for FR</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>FR_sales <span class="op">=</span> sales_count.iloc[<span class="dv">0</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The proportion of FR sales</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>prob_fr <span class="op">=</span> FR_sales<span class="op">/</span> total_sales</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The proportion of flat rate price is </span><span class="sc">{</span>prob_fr<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co">#number of sales for FR Charity</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>FR_charity_sales <span class="op">=</span> sales_count.iloc[<span class="dv">1</span>]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># The proportion of FR Charity sales</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>prob_fr_charity <span class="op">=</span> sales_count.iloc[<span class="dv">1</span>]<span class="op">/</span> total_sales</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The proportion of flat rate price charity is </span><span class="sc">{</span>prob_fr_charity<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The proportion of flat rate price is 0.031229087664510373
The proportion of flat rate price charity is 0.04015168414008476</code></pre>
</div>
</div>
<p>To determine whether FR and FR Charity are difference proportion of purchase, we use the hypothesis test. The null hypothesis is that the proportion of purchase is the same for FR and FR Charity. The alternative hypothesis is that the proportion of purchase is different for FR and FR Charity.</p>
<p>The hypothesis is:</p>
<p><span class="math display">\[H_0: p_{FR} = p_{FR \; Charity}\]</span> <span class="math display">\[H_a: p_{FR} \neq p_{FR \; Charity}\]</span></p>
<p>Where <span class="math inline">\(p_{FR}\)</span> is the proportion of purchase for FR and <span class="math inline">\(p_{FR \; Charity}\)</span> is the proportion of purchase for FR Charity.</p>
<div id="71b64be7" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find z test statistic</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>numerator <span class="op">=</span> prob_fr <span class="op">-</span> prob_fr_charity</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>denominator <span class="op">=</span> np.sqrt((prob_fr <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> prob_fr))<span class="op">/</span>FR_sales <span class="op">+</span> (prob_fr_charity <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> prob_fr_charity))<span class="op">/</span>FR_charity_sales)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>z_score <span class="op">=</span> numerator<span class="op">/</span>denominator</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"z_score is </span><span class="sc">{</span>z_score<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># find p value</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> (<span class="dv">1</span> <span class="op">-</span> (norm.sf(z_score)))<span class="op">*</span><span class="dv">2</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p_value is </span><span class="sc">{</span>p_value<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>z_score is -0.43018214003639416
p_value is 0.6670631527631585</code></pre>
</div>
</div>
<p>Assume that confidence level in this case is 95% . So we will reject null hypothesis if Z_score <span class="math inline">\(\geq\)</span> -1.96 or Z_score <span class="math inline">\(\leq\)</span> 1.96</p>
<p>We have Z_score = -0.43 which is not in the rejection region. So we can not reject the null hypothesis. It means that the proportion of purchase is the same for FR and FR Charity.</p>
<p>Now for the <span class="math inline">\(p\)</span> approach, let’s manually calculate the p-value. We have:</p>
<p><span class="math inline">\(p\)</span> = P(Z <span class="math inline">\(\geq\)</span> 0.43 or Z <span class="math inline">\(\leq\)</span> -0.43) = 2 * P(Z <span class="math inline">\(\leq\)</span> -0.43) = 2 * 0.332 = 0.664 <span class="math inline">\(\sim\)</span> 0.667 above</p>
<p>So <span class="math inline">\(p\)</span> = 0.664 &gt; 0.05. It means that we do not have enough evidence to reject the null hypothesis.</p>
<section id="nyop-pricing" class="level2">
<h2 class="anchored" data-anchor-id="nyop-pricing">NYOP PRICING</h2>
<div id="f1430d3d" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># number of sales for NYOP</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>nyop_sale <span class="op">=</span> sales_count.iloc[<span class="dv">2</span>]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The proportion of NYOP sales</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>prob_nyop <span class="op">=</span> nyop_sale<span class="op">/</span> total_sales</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The proportion of NYOP is </span><span class="sc">{</span>prob_nyop<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># number of sales for NYOP Charity</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>nyop_charity_sales <span class="op">=</span> sales_count.iloc[<span class="dv">3</span>]</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co"># The proportion of NYOP Charity sales</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>prob_nyop_charity <span class="op">=</span> nyop_charity_sales<span class="op">/</span> total_sales</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The proportion of NYOP Charity is </span><span class="sc">{</span>prob_nyop_charity<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The proportion of NYOP is 0.5286638411777828
The proportion of NYOP Charity is 0.3999553870176221</code></pre>
</div>
</div>
<p>To determine whether NYOP and NYOP Charity are difference proportion of purchase, we use the hypothesis test. The null hypothesis is that the proportion of purchase is the same for NYOP and NYOP Charity. The alternative hypothesis is that the proportion of purchase is different for NYOP and NYOP Charity.</p>
<p>The hypothesis is:</p>
<p><span class="math display">\[H_0: p_{NYOP} = p_{NYOP \; Charity}\]</span> <span class="math display">\[H_a: p_{NYOP} \neq p_{NYOP \; Charity}\]</span></p>
<p>Where <span class="math inline">\(p_{NYOP}\)</span> is the proportion of purchase for NYOP and <span class="math inline">\(p_{NYOP \; Charity}\)</span> is the proportion of purchase for NYOP Charity.</p>
<div id="034e82b9" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find z test statistic</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>numerator <span class="op">=</span> prob_nyop <span class="op">-</span> prob_nyop_charity</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>denominator <span class="op">=</span> np.sqrt((prob_nyop <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> prob_nyop))<span class="op">/</span>nyop_sale <span class="op">+</span> (prob_nyop_charity <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> prob_nyop_charity))<span class="op">/</span>nyop_charity_sales)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>z_score <span class="op">=</span> numerator<span class="op">/</span>denominator</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"z_score is </span><span class="sc">{</span>z_score<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># find p value</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> norm.sf((z_score))<span class="op">*</span><span class="dv">2</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p_value is </span><span class="sc">{</span>p_value<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>z_score is 8.325676265627516
p_value is 8.38486658961012e-17</code></pre>
</div>
</div>
<p>Assume that confident level in this case is 95% . So we will reject null hypothesis if Z_score <span class="math inline">\(\geq\)</span> -1.96 or Z_score <span class="math inline">\(\leq\)</span> 1.96</p>
<p>We have Z_score = 8.33 which is in the rejection region. So we can reject the null hypothesis. It means that the proportion of purchase is different for NYOP and NYOP Charity.</p>
<p>Now for the <span class="math inline">\(p\)</span> approach:</p>
<p><span class="math inline">\(p\)</span> = P(Z <span class="math inline">\(\geq\)</span> 8.32 or Z <span class="math inline">\(\leq\)</span> -8.32) = 2 * P(Z <span class="math inline">\(\leq\)</span> -8.32) = 2 * 0 = 0</p>
<p>That is, the <span class="math inline">\(p\)</span> value is less than 0.0001. Because P_value &lt; 0.05, we can reject the null hypothesis. Again, there is sufficient evidence at the 0.05 level to conclude that the proportion of purchase is different for NYOP and NYOP Charity.</p>
<div id="c006cb9f" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load NYOP data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>nyop <span class="op">=</span> pd.read_csv(<span class="st">'NYOP.csv'</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(nyop.head(<span class="dv">15</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Condition  Number  Price
0       NYOP       1   1.00
1       NYOP       1   1.00
2       NYOP       1   0.01
3       NYOP       1   0.10
4       NYOP       1   0.01
5       NYOP       2   0.02
6       NYOP       1   5.00
7       NYOP       1   1.00
8       NYOP       2   0.02
9       NYOP       1   0.05
10      NYOP       1   0.75
11      NYOP       1   1.50
12      NYOP       1   0.20
13      NYOP       1   0.01
14      NYOP       1   1.00</code></pre>
</div>
</div>
<div id="57e312fd" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a new column for unit price</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>nyop[<span class="st">'UnitPrice'</span>] <span class="op">=</span> nyop[<span class="st">'Price'</span>] <span class="op">/</span> nyop[<span class="st">'Number'</span>]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the data type of "Number" column to a factor:</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>nyop[<span class="st">'Number'</span>] <span class="op">=</span> nyop[<span class="st">'Number'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>nyop.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Condition</th>
<th data-quarto-table-cell-role="th">Number</th>
<th data-quarto-table-cell-role="th">Price</th>
<th data-quarto-table-cell-role="th">UnitPrice</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>NYOP</td>
<td>1</td>
<td>1.00</td>
<td>1.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>NYOP</td>
<td>1</td>
<td>1.00</td>
<td>1.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>NYOP</td>
<td>1</td>
<td>0.01</td>
<td>0.01</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>NYOP</td>
<td>1</td>
<td>0.10</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>NYOP</td>
<td>1</td>
<td>0.01</td>
<td>0.01</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>Visualize both Price and UnitPrice against the factor variable Number</p>
<div id="afbc85aa" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set style</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">"whitegrid"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a 1x2 subplot to visualize both Price and UnitPrice</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">6</span>))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot for Price vs Number</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'Number'</span>, y<span class="op">=</span><span class="st">'Price'</span>, data<span class="op">=</span>nyop, ax<span class="op">=</span>axes[<span class="dv">0</span>])</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Boxplot of Price vs Number'</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Price'</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Number'</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot for UnitPrice vs Number</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'Number'</span>, y<span class="op">=</span><span class="st">'UnitPrice'</span>, data<span class="op">=</span>nyop, ax<span class="op">=</span>axes[<span class="dv">1</span>])</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Boxplot of UnitPrice vs Number'</span>)</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">'UnitPrice'</span>)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">'Number'</span>)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust layout</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Shared_social_group_files/figure-html/cell-10-output-1.png" width="1430" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(\textit{Boxplot of Price vs. Number:}\)</span></p>
<ul>
<li><p>The median price generally increases as the number increases.</p></li>
<li><p>The variability (as shown by the height of the boxes) also seems to increase with the number. This means that as the number increases, the prices are spread out over a wider range.</p></li>
<li><p>There are some outliers, especially for lower numbers.</p></li>
</ul>
<p><span class="math inline">\(\textit{Boxplot of UnitPrice vs. Number:}\)</span></p>
<ul>
<li><p>The median unit price is consistent across the different numbers. This is expected, as the unit price is simply the price divided by the number.</p></li>
<li><p>The variability of unit prices decreases as the number increases. For number 1, there’s a wide range of unit prices, but this range narrows down for higher numbers.</p></li>
<li><p>As with the price, there are some outliers for lower numbers in unit price.</p></li>
</ul>
<p>In summary, while the absolute price increases with the number and has increasing variability, the unit price seems relatively consistent across different numbers but with decreasing variability.</p>
<ol start="3" type="a">
<li>Determine the average unit purchase price for both the NYOP and the NYOP Charity conditions</li>
</ol>
<div id="8c06aef2" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the average unit price of each condition</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>x_bar <span class="op">=</span> nyop.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'UnitPrice'</span>].mean()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the average unit price of NYOP</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>x_bar_nyop <span class="op">=</span> x_bar.iloc[<span class="dv">0</span>]</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The average unit price of NYOP is </span><span class="sc">{</span>x_bar_nyop<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the average unit price of NYOP</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>x_bar_nyop_charity <span class="op">=</span> x_bar.iloc[<span class="dv">1</span>]</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The average unit price of NYOP Charity is </span><span class="sc">{</span>x_bar_nyop_charity<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The average unit price of NYOP is 1.040438756855576
The average unit price of NYOP Charity is 5.680480439258751</code></pre>
</div>
</div>
<p>If we only look at the result above, the different between NYOP and NYOP charity is substantial. However, to determine whether the different between average unit price for NYOP and NYOP Charity is statistically significant, we use T-distribution test. The null hypothesis is that the average unit price for NYOP and NYOP Charity is the same. The alternative hypothesis is that the average unit price for NYOP and NYOP Charity is different.</p>
<p>The hypothesis test is: <span class="math display">\[H_0: \mu_{nyop} - \mu_{nyop\;charity} = 0\]</span> <span class="math display">\[H_a: \mu_{nyop} - \mu_{nyop\;charity} \neq 0\]</span></p>
<p>Where:</p>
<p><span class="math inline">\(\mu_{nyop}\)</span> is the average unit price for NYOP</p>
<p><span class="math inline">\(\mu_{nyop\;charity}\)</span> is the average unit price for NYOP Charity</p>
<ol start="5" type="a">
<li>Use the pyrsm library to perform the test computation (Compare means)</li>
</ol>
<div id="fefb18ad" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>nyop_test <span class="op">=</span> rsm.basics.compare_means({<span class="st">"data"</span>: nyop}, var1 <span class="op">=</span> <span class="st">"Condition"</span>, var2 <span class="op">=</span> <span class="st">"UnitPrice"</span>, alt_hyp <span class="op">=</span> <span class="st">"two-sided"</span>, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                                     sample_type<span class="op">=</span><span class="st">'independent'</span>, conf <span class="op">=</span> <span class="fl">0.95</span>, test_type<span class="op">=</span><span class="st">"t-test"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>nyop_test.summary(extra <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pairwise mean comparisons (t-test)
Data      : data
Variables : Condition, UnitPrice
Samples   : independent
Confidence: 0.95
Adjustment: None
   Condition  mean    n  n_missing    sd    se    me
        NYOP  1.04 1641          0 1.305 0.032 0.063
NYOP Charity  5.68 1457          0 4.670 0.122 0.240
          Null hyp.                      Alt. hyp.  diff p.value    se  t.value       df   2.5%  97.5%    
NYOP = NYOP Charity NYOP not equal to NYOP Charity -4.64  &lt; .001 0.127  -36.676 1657.943 -4.888 -4.392 ***

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="do-analytics-by-hand" class="level5">
<h5 class="anchored" data-anchor-id="do-analytics-by-hand">Do analytics by hand</h5>
<div id="0b2c097c" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the standard deviation of the sample</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> nyop.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'UnitPrice'</span>].std()</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard deviation of NYOP</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>s_nyop <span class="op">=</span> s.iloc[<span class="dv">0</span>]</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The standard deviation of NYOP is </span><span class="sc">{</span>s_nyop<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard deviation of NYOP Charity</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>s_nyop_charity <span class="op">=</span> s.iloc[<span class="dv">1</span>]</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The standard deviation of NYOP Charity is </span><span class="sc">{</span>s_nyop_charity<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the sample size</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> nyop.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'UnitPrice'</span>].count()</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size of NYOP</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>n_nyop <span class="op">=</span> n.iloc[<span class="dv">0</span>]</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The sample size of NYOP is </span><span class="sc">{</span>n_nyop<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size of NYOP Charity</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>n_nyop_charity <span class="op">=</span> n.iloc[<span class="dv">1</span>]</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The sample size of NYOP Charity is </span><span class="sc">{</span>n_nyop_charity<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The standard deviation of NYOP is 1.3053709602869232
The standard deviation of NYOP Charity is 4.669903393923693
The sample size of NYOP is 1641
The sample size of NYOP Charity is 1457</code></pre>
</div>
</div>
<div id="04fe840c" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Find t test statistic</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>t_value <span class="op">=</span> (x_bar_nyop <span class="op">-</span> x_bar_nyop_charity)<span class="op">/</span>np.sqrt((s_nyop<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop) <span class="op">+</span> (s_nyop_charity<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop_charity))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'T_value is </span><span class="sc">{</span>t_value<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Find degree of freedom</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> (s_nyop<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop)<span class="op">/</span>(s_nyop<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop<span class="op">+</span>s_nyop_charity<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop_charity)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>numerator <span class="op">=</span> (n_nyop<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>(n_nyop_charity<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>denominator <span class="op">=</span> (n_nyop_charity<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>(a<span class="op">**</span><span class="dv">2</span>) <span class="op">+</span> (n_nyop<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>((<span class="dv">1</span><span class="op">-</span>a)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>degree_of_freedom <span class="op">=</span> numerator<span class="op">/</span>denominator</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Degree of freedom is </span><span class="sc">{</span>degree_of_freedom<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Find p value</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> t.sf(<span class="bu">abs</span>(t_value), degree_of_freedom)<span class="op">*</span><span class="dv">2</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P_test is </span><span class="sc">{</span>p_value<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T_value is -36.675728193478896
Degree of freedom is 1657.9433648647218
P_test is 3.954550853548388e-216</code></pre>
</div>
</div>
<p>Based on the result showing in both radiant and analysis by hand:</p>
<p><span class="math inline">\(p\)</span> value = 0.000 &lt; 0.05. So we have enough to reject the null hypothesis. It means that the average unit price for NYOP and NYOP Charity are different.</p>
</section>
<section id="in-hypothesis-testing" class="level4">
<h4 class="anchored" data-anchor-id="in-hypothesis-testing">In hypothesis testing:</h4>
<p>Type I Error (<span class="math inline">\(α\)</span>): This occurs when we incorrectly reject a true null hypothesis. It’s also known as a “false positive.”</p>
<p>Type II Error (<span class="math inline">\(β\)</span>): This occurs when we fail to reject a false null hypothesis. It’s also known as a “false negative.”</p>
<p>In this case, <span class="math inline">\(p\)</span> value is extremely small, so we can reject the null hypothesis. But if the true state is that the average unit price for NYOP and NYOP Charity is the same, we will make a Type I Error. However, given the extremely small <span class="math inline">\(p\)</span> value, the probability of making a Type I Error is very small.</p>
</section>
<section id="the-difference-between-nyop-and-nyop-charity-for-those-who-purchase-1-picture" class="level3">
<h3 class="anchored" data-anchor-id="the-difference-between-nyop-and-nyop-charity-for-those-who-purchase-1-picture">The difference between NYOP and NYOP Charity for those who purchase 1 picture</h3>
<p>To determine whether the different between average unit price for NYOP and NYOP Charity is statistically significant, we use T-distribution test. The null hypothesis is that the average unit price for NYOP and NYOP Charity is the same. The alternative hypothesis is that the average unit price for NYOP and NYOP Charity is different.</p>
<p>The hypothesis test is: <span class="math display">\[H_0: \mu_{nyop} - \mu_{nyop\;charity} = 0\]</span> <span class="math display">\[H_a: \mu_{nyop} - \mu_{nyop\;charity} \neq 0\]</span></p>
<p>Where:</p>
<p><span class="math inline">\(\mu_{nyop}\)</span> is the average unit price for NYOP</p>
<p><span class="math inline">\(\mu_{nyop\;charity}\)</span> is the average unit price for NYOP Charity</p>
<div id="c9968f8f" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data to only include people who purchase one photo</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>one_photo <span class="op">=</span> nyop[nyop[<span class="st">'Number'</span>] <span class="op">==</span> <span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="3c9fdf98" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use radiant to check the result</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>one_photo_test <span class="op">=</span> rsm.basics.compare_means({<span class="st">"one_photo"</span>: one_photo}, var1 <span class="op">=</span> <span class="st">"Condition"</span>, var2 <span class="op">=</span> <span class="st">"UnitPrice"</span>, alt_hyp <span class="op">=</span> <span class="st">"two-sided"</span>, </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                                     sample_type<span class="op">=</span><span class="st">'independent'</span>, conf <span class="op">=</span> <span class="fl">0.95</span>, test_type<span class="op">=</span><span class="st">"t-test"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>one_photo_test.summary(extra <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pairwise mean comparisons (t-test)
Data      : one_photo
Variables : Condition, UnitPrice
Samples   : independent
Confidence: 0.95
Adjustment: None
   Condition  mean    n  n_missing    sd    se    me
        NYOP 1.177 1162          0 1.432 0.042 0.082
NYOP Charity 5.941 1203          0 4.830 0.139 0.273
          Null hyp.                      Alt. hyp.   diff p.value    se  t.value       df  2.5%  97.5%    
NYOP = NYOP Charity NYOP not equal to NYOP Charity -4.765  &lt; .001 0.145  -32.755 1418.571 -5.05 -4.479 ***

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="do-analysis-by-hand" class="level4">
<h4 class="anchored" data-anchor-id="do-analysis-by-hand">Do analysis by hand</h4>
<div id="6f70afb3" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find t test statistic</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>t_value <span class="op">=</span> (x_bar_nyop <span class="op">-</span> x_bar_nyop_charity)<span class="op">/</span>np.sqrt((s_nyop<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop) <span class="op">+</span> (s_nyop_charity<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop_charity))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'T_value is </span><span class="sc">{</span>t_value<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Find degree of freedom</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> (s_nyop<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop)<span class="op">/</span>(s_nyop<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop<span class="op">+</span>s_nyop_charity<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop_charity)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>numerator <span class="op">=</span> (n_nyop<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>(n_nyop_charity<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>denominator <span class="op">=</span> (n_nyop_charity<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>(a<span class="op">**</span><span class="dv">2</span>) <span class="op">+</span> (n_nyop<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>((<span class="dv">1</span><span class="op">-</span>a)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>degree_of_freedom <span class="op">=</span> numerator<span class="op">/</span>denominator</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Degree of freedom is </span><span class="sc">{</span>degree_of_freedom<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Find p value</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> t.sf(<span class="bu">abs</span>(t_value), degree_of_freedom)<span class="op">*</span><span class="dv">2</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P_value is </span><span class="sc">{</span>p_value<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T_value is -36.675728193478896
Degree of freedom is 1657.9433648647218
P_value is 3.954550853548388e-216</code></pre>
</div>
</div>
<div id="fc1352b8" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the average unit price of each condition</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>x_bar <span class="op">=</span> one_photo.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'UnitPrice'</span>].mean()</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the average unit price of NYOP</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>x_bar_nyop <span class="op">=</span> x_bar.iloc[<span class="dv">0</span>]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The average unit price of NYOP is </span><span class="sc">{</span>x_bar_nyop<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the average unit price of NYOP Charity</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>x_bar_nyop_charity <span class="op">=</span> x_bar.iloc[<span class="dv">1</span>]</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The average unit price of NYOP Charity is </span><span class="sc">{</span>x_bar_nyop_charity<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the standard deviation of the sample</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> one_photo.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'UnitPrice'</span>].std()</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard deviation of NYOP</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>s_nyop <span class="op">=</span> s.iloc[<span class="dv">0</span>]</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The standard deviation of NYOP is </span><span class="sc">{</span>s_nyop<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard deviation of NYOP Charity</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>s_nyop_charity <span class="op">=</span> s.iloc[<span class="dv">1</span>]</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The standard deviation of NYOP Charity is </span><span class="sc">{</span>s_nyop_charity<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the sample size</span></span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> one_photo.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'UnitPrice'</span>].count()</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size of NYOP</span></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>n_nyop <span class="op">=</span> n.iloc[<span class="dv">0</span>]</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The sample size of NYOP is </span><span class="sc">{</span>n_nyop<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size of NYOP Charity</span></span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>n_nyop_charity <span class="op">=</span> n.iloc[<span class="dv">1</span>]</span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The sample size of NYOP Charity is </span><span class="sc">{</span>n_nyop_charity<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The average unit price of NYOP is 1.1765232358003443
The average unit price of NYOP Charity is 5.941155444721529
The standard deviation of NYOP is 1.4321112974184242
The standard deviation of NYOP Charity is 4.830261504439939
The sample size of NYOP is 1162
The sample size of NYOP Charity is 1203</code></pre>
</div>
</div>
</section>
</section>
<section id="the-difference-between-nyop-and-nyop-charity-for-those-who-purchase-6-pictures" class="level3">
<h3 class="anchored" data-anchor-id="the-difference-between-nyop-and-nyop-charity-for-those-who-purchase-6-pictures">The difference between NYOP and NYOP Charity for those who purchase 6 pictures</h3>
<div id="eefe51d3" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data to only include people who purchase 6 photos</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>six_photos <span class="op">=</span> nyop[nyop[<span class="st">'Number'</span>] <span class="op">==</span> <span class="dv">6</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="c506e28e" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the pyrsm to perform t test</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>six_photo_test <span class="op">=</span> rsm.basics.compare_means({<span class="st">"six_photos"</span>: six_photos}, var1 <span class="op">=</span> <span class="st">"Condition"</span>, var2 <span class="op">=</span> <span class="st">"UnitPrice"</span>, alt_hyp <span class="op">=</span> <span class="st">"two-sided"</span>, </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                                     sample_type<span class="op">=</span><span class="st">'independent'</span>, conf <span class="op">=</span> <span class="fl">0.95</span>, test_type<span class="op">=</span><span class="st">"t-test"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>six_photo_test.summary(extra <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pairwise mean comparisons (t-test)
Data      : six_photos
Variables : Condition, UnitPrice
Samples   : independent
Confidence: 0.95
Adjustment: None
   Condition  mean  n  n_missing    sd    se    me
        NYOP 0.495  6          0 0.615 0.251 0.646
NYOP Charity 1.970  3          0 1.795 1.036 4.459
          Null hyp.                      Alt. hyp.   diff p.value    se  t.value    df   2.5%  97.5%  
NYOP = NYOP Charity NYOP not equal to NYOP Charity -1.475   0.288 1.066   -1.383 2.239 -5.625  2.675  

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="do-analysis-by-hand-1" class="level5">
<h5 class="anchored" data-anchor-id="do-analysis-by-hand-1">Do Analysis by hand:</h5>
<div id="64326db1" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the average unit price of each condition</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>x_bar <span class="op">=</span> six_photos.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'UnitPrice'</span>].mean()</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the average unit price of NYOP</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>x_bar_nyop <span class="op">=</span> x_bar.iloc[<span class="dv">0</span>]</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The average unit price of NYOP is </span><span class="sc">{</span>x_bar_nyop<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the average unit price of NYOP Charity</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>x_bar_nyop_charity <span class="op">=</span> x_bar.iloc[<span class="dv">1</span>]</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The average unit price of NYOP Charity is </span><span class="sc">{</span>x_bar_nyop_charity<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the standard deviation of the sample</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> six_photos.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'UnitPrice'</span>].std()</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard deviation of NYOP</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>s_nyop <span class="op">=</span> s.iloc[<span class="dv">0</span>]</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The standard deviation of NYOP is </span><span class="sc">{</span>s_nyop<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard deviation of NYOP Charity</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>s_nyop_charity <span class="op">=</span> s.iloc[<span class="dv">1</span>]</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The standard deviation of NYOP Charity is </span><span class="sc">{</span>s_nyop_charity<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the sample size</span></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> six_photos.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'UnitPrice'</span>].count()</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size of NYOP</span></span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>n_nyop <span class="op">=</span> n.iloc[<span class="dv">0</span>]</span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The sample size of NYOP is </span><span class="sc">{</span>n_nyop<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size of NYOP Charity</span></span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>n_nyop_charity <span class="op">=</span> n.iloc[<span class="dv">1</span>]</span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The sample size of NYOP Charity is </span><span class="sc">{</span>n_nyop_charity<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The average unit price of NYOP is 0.49499999999999994
The average unit price of NYOP Charity is 1.97
The standard deviation of NYOP is 0.6152316636845019
The standard deviation of NYOP Charity is 1.7951880124376947
The sample size of NYOP is 6
The sample size of NYOP Charity is 3</code></pre>
</div>
</div>
<div id="7f8e9716" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find t test statistic</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>t_value <span class="op">=</span> (x_bar_nyop <span class="op">-</span> x_bar_nyop_charity)<span class="op">/</span>np.sqrt((s_nyop<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop) <span class="op">+</span> (s_nyop_charity<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop_charity))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'T_value is </span><span class="sc">{</span>t_value<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Find degree of freedom</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> (s_nyop<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop)<span class="op">/</span>(s_nyop<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop<span class="op">+</span>s_nyop_charity<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n_nyop_charity)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>numerator <span class="op">=</span> (n_nyop<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>(n_nyop_charity<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>denominator <span class="op">=</span> (n_nyop_charity<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>(a<span class="op">**</span><span class="dv">2</span>) <span class="op">+</span> (n_nyop<span class="op">-</span><span class="dv">1</span>)<span class="op">*</span>((<span class="dv">1</span><span class="op">-</span>a)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>degree_of_freedom <span class="op">=</span> numerator<span class="op">/</span>denominator</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Degree of freedom is </span><span class="sc">{</span>degree_of_freedom<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Find p value</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> t.sf(<span class="bu">abs</span>(t_value), degree_of_freedom)<span class="op">*</span><span class="dv">2</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P_value is </span><span class="sc">{</span>p_value<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T_value is -1.3830917803702294
Degree of freedom is 2.238711549258564
P_value is 0.2884114566627225</code></pre>
</div>
</div>
<p><span class="math inline">\(p\)</span> value = 0.3 &gt; 0.05. So we do not have enough to reject the null hypothesis. It means that the difference between NYOP and NYOP Charity for those who purchase 6 pictures is not statistically significant.</p>
<p>The result showing in both Radiant and analysis by hand are the same. In general, manual calculations and standard statistical software should yield the same results, given the same data and assumptions. Any discrepancy would either be due to an error in computation or different assumptions/methodologies applied.</p>
<p><span class="math inline">\(p\)</span> value = 0.002 &lt; 0.05. So we have enough evidence to reject the null hypothesis. It means that the average purchase of 1 photo and 6 photos are different. Again, we have the same result as above because the data size is large enough.</p>
</section>
</section>
</section>
<section id="economics" class="level1">
<h1>Economics</h1>
<div id="68790fc3" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add cost and profit column to sales data</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>sales[<span class="st">'Cost'</span>] <span class="op">=</span> sales[<span class="st">'NumberSold'</span>] <span class="op">*</span> <span class="fl">1.2</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>sales[<span class="st">'Merchandise_Profit'</span>] <span class="op">=</span> sales[<span class="st">'MerchandiseRevenues'</span>] <span class="op">-</span> sales[<span class="st">'Cost'</span>]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the average profit of each condition</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>avg_profit <span class="op">=</span> sales.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'Merchandise_Profit'</span>].mean()</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(avg_profit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Condition
FR              5556.49
FR Charity      6053.36
NYOP            4519.95
NYOP Charity    6033.30
Name: Merchandise_Profit, dtype: float64</code></pre>
</div>
</div>
<p>Due to the data on Avg_profit table, The “FR Charity” option has the highest value of $6053.36, making it the most profitable option among the ones listed And the ranking is: FR Charity &gt; FR &gt; NYOP Charity &gt; NYOP</p>
<p>When think about additional value created by FR charity and NYOP charity, we need to consider both theme park’s profits and the profits directed towards to the charity. In this case, we have:</p>
<p>Charity Profit = 0.5 × Merchandise Revenues</p>
<p>Theme Park Profit = Merchandise Revenues − Cost of Photos − Charity Profit = Merchandise Profit - Charity Profit</p>
<p>Societal Profit = Charity Profit + Theme Park Profit</p>
<div id="8aa72397" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> societal_profit(row):</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> row[<span class="st">'Condition'</span>] <span class="kw">in</span> [<span class="st">'FR Charity'</span>, <span class="st">'NYOP Charity'</span>]:</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>        charity_profit <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> row[<span class="st">'MerchandiseRevenues'</span>]</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>        theme_park_profit <span class="op">=</span> row[<span class="st">'Merchandise_Profit'</span>] <span class="op">-</span> charity_profit</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> charity_profit <span class="op">+</span> theme_park_profit</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> row[<span class="st">'Merchandise_Profit'</span>]</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>sales[<span class="st">'SocietalProfit'</span>] <span class="op">=</span> sales.<span class="bu">apply</span>(societal_profit, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sales.head(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Condition  NumberSold  Riders  MerchandiseRevenues    Cost  \
0            FR          77   12663              4592.41    92.4   
1            FR          63   15561              6688.57    75.6   
2    FR Charity          79   14796              6476.78    94.8   
3    FR Charity         101   15796              5845.94   121.2   
4          NYOP        1137   14077              4845.27  1364.4   
5          NYOP        1233   14186              7038.63  1479.6   
6  NYOP Charity         539   12227              5690.59   646.8   
7  NYOP Charity         628   13741              6003.44   753.6   
8  NYOP Charity         626   18117              8557.47   751.2   

   Merchandise_Profit  SocietalProfit  
0             4500.01         4500.01  
1             6612.97         6612.97  
2             6381.98         6381.98  
3             5724.74         5724.74  
4             3480.87         3480.87  
5             5559.03         5559.03  
6             5043.79         5043.79  
7             5249.84         5249.84  
8             7806.27         7806.27  </code></pre>
</div>
</div>
<div id="ff39bbd1" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find average societal profit of each condition</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>avg_societal_profit <span class="op">=</span> sales.groupby(<span class="st">"Condition"</span>, observed<span class="op">=</span><span class="va">False</span>)[<span class="st">'SocietalProfit'</span>].mean()</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(avg_societal_profit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Condition
FR              5556.49
FR Charity      6053.36
NYOP            4519.95
NYOP Charity    6033.30
Name: SocietalProfit, dtype: float64</code></pre>
</div>
</div>
<p>By the results above, FR and NYOP do not have charity profit, so the societal profit is the same as merchandise profit.</p>
<p>Considering societal profits, which include both theme park’s profits and the contributions to charity, the ranking is: FR Charity &gt; NYOP Charity</p>
<p>If considering all condition, the ranking will be: FR Charity &gt; NYOP Charity &gt; FR &gt; NYOP</p>
<p>The rankings indicate that the charity conditions (FR Charity and NYOP Charity) not only benefit the theme park but also significantly contribute to societal value, making them the top two strategies in terms of societal profits.</p>
<ol start="4" type="a">
<li>To determine how much additional societal profit the leading strategy (“FR Charity”) generates over the others over the entire year, we’ll:</li>
</ol>
<ul>
<li><p>Calculate the yearly societal profit for the leading strategy by multiplying its average daily profit by 365.</p></li>
<li><p>Calculate the yearly societal profit for each of the other strategies.</p></li>
<li><p>Subtract the yearly societal profit of each of the other strategies from that of the leading strategy to determine the difference.</p></li>
</ul>
<div id="b2e778ed" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate yearly societal profit for each strategy</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>yearly_societal_profit <span class="op">=</span> avg_societal_profit <span class="op">*</span> <span class="dv">365</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the additional profit the leading strategy generates over the others</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>additional_profit <span class="op">=</span> yearly_societal_profit[<span class="st">'FR Charity'</span>] <span class="op">-</span> yearly_societal_profit</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>additional_profit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>Condition
FR              181357.55
FR Charity           0.00
NYOP            559694.65
NYOP Charity      7321.90
Name: SocietalProfit, dtype: float64</code></pre>
</div>
</div>
<p>Over the entire year (assuming 365 days), the leading strategy “FR Charity” generates the following additional societal profits over the other strategies:</p>
<ul>
<li><p>$181,357.55 more than the “FR” strategy.</p></li>
<li><p>$559,694.65 more than the “NYOP” strategy.</p></li>
<li><p>$7,321.90 more than the “NYOP Charity” strategy.</p></li>
</ul>
<p>This analysis underscores the significant societal value that the “FR Charity” strategy offers compared to the other strategies over the course of a year.</p>
<p><strong>Summary:</strong></p>
<p>FR Strategy:</p>
<ul>
<li>Total photos sold: 140</li>
<li>Average photos sold per day: 70</li>
<li>Total merchandise revenues: $11,280.98</li>
<li>Average merchandise revenue per day: $5,640.49</li>
</ul>
<p>FR Charity Strategy:</p>
<ul>
<li>Total photos sold: 180</li>
<li>Average photos sold per day: 90</li>
<li>Total merchandise revenues: $12,322.72</li>
<li>Average merchandise revenue per day: $6,161.36</li>
</ul>
<p>NYOP Strategy:</p>
<ul>
<li>Total photos sold: 2,370</li>
<li>Average photos sold per day: 1,185</li>
<li>Total merchandise revenues: $11,883.90</li>
<li>Average merchandise revenue per day: $5,941.95</li>
</ul>
<p>NYOP Charity Strategy:</p>
<ul>
<li>Total photos sold: 1,793</li>
<li>Average photos sold per day: 597.67</li>
<li>Total merchandise revenues: $20,251.50</li>
<li>Average merchandise revenue per day: $6,750.50</li>
</ul>
<p>From the summary:</p>
<p>The NYOP strategy has the highest number of photos sold, both in total and on average daily. However, its average merchandise revenue is not the highest, which suggests that photos under this strategy might be priced lower.</p>
<p>The NYOP Charity strategy has the highest average and total merchandise revenues, even though it doesn’t have the highest number of photos sold. This suggests that the photos under this strategy might be priced higher or that people might be more willing to buy when they know a portion goes to charity.</p>
<p>Whether or not merchandise sales are a concern depends on the goals and expectations of the theme park. If the aim is to maximize revenues, the current data suggests the “NYOP Charity” strategy is performing well. If the goal is to sell the most photos, then the “NYOP” strategy is leading.</p>
<p>But when considering about profit, the FR Charity strategy is the best option even though it doesn’t have the highest average and total merchandise revenues. This suggests that the FR Charity strategy is the best option for the theme park, as it maximizes both revenues and profits.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>